
AceLibrary("AceLocale-2.2"):new("Visor2_GUI"):RegisterTranslations("enUS", function() return {
	["Visor2 GUI"] = true,
	["Toggle GUI Frame"] = true,

	["Grab"] = true,
	["Grab Parent"] = true,
	["Done"] = true,
	["Cancel"] = true,
	["Delete"] = true,
	["None"] = true,
	["Virtual"] = true,

	["Are you sure you want to delete this frame's settings?"] = true,
	["You will need to Reload UI for any changes to take effect"] = true,
	["Enter frame name or select frame with Grab button"] = true,
	["Drag mouse and release on target frame"] = true,

	["Nudge Left"] = true,
	["Nudge Right"] = true,
	["Nudge Up"] = true,
	["Nudge Down"] = true,
	["Nudge Amount"] = true,
	["Width Up"] = true,
	["Width Down"] = true,
	["Height Up"] = true,
	["Height Down"] = true,

	["Left-Click and hold the mouse button, move the mouse over a frame and release the button to select that frame"] = true,
	["Set the active frame's parent frame as the active frame"] = true,
	["Parent Frame"] = true,
	["Exit Visor2 GUI"] = true,
	["Delete the selected frame's settings from Visor2"] = true,
	["Show/Hide the selected frame"] = true,
	["Hide Frame"] = true,
	["Show Frame"] = true,
	["Adjust frame size"] = true,
	["Frame Scale"] = true,
	["Adjust frame transparency"] = true,
	["Frame Alpha"] = true,
	["Enter Width"] = true,
	["Frame Width"] = true,
	["Enter Height"] = true,
	["Frame Height"] = true,
	["Enter X co-ordinate (center point of frame)"] = true,
	["Enter Y co-ordinate (center point of frame)"] = true,
	["Show a virtual copy of a hidden frame"] = true,
} end)
